# Generated by Django 3.2 on 2023-02-20 14:26

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('image', models.ImageField(upload_to='categoryImg/', verbose_name='Картинка')),
                ('desc', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='postcode',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('desc', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('main_img', models.ImageField(upload_to='images/', verbose_name='Главная Фотография')),
                ('image1', models.ImageField(upload_to='images/', verbose_name='Фотография 1')),
                ('image2', models.ImageField(upload_to='images/', verbose_name='Фотография 2')),
                ('image3', models.ImageField(upload_to='images/', verbose_name='Фотография 3')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=100000000)),
                ('stock', models.BooleanField(default=True)),
                ('made', models.CharField(choices=[('TURC', 'Турция'), ('UZB', 'Узбексиатн'), ('CHIN', 'Китай')], max_length=512, verbose_name='Изготовление')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('color', models.ManyToManyField(to='shop.Color')),
                ('size', models.ManyToManyField(to='shop.Size')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
