# Generated by Django 3.2 on 2023-02-22 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230222_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название*')),
                ('image', models.ImageField(upload_to='brandImg/', verbose_name='Картинка*')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='product',
            name='made',
            field=models.CharField(choices=[('TURC', 'Турция'), ('UZB', 'Узбексиатн'), ('CHIN', 'Китай'), ('USA', 'США')], max_length=512, verbose_name='Изготовление*'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.brand', verbose_name='Бренд*'),
            preserve_default=False,
        ),
    ]
