# Generated by Django 3.2 on 2023-02-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20230222_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=250, verbose_name='Бренд*'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
